# Generated by Django 2.1.4 on 2018-12-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_auto_20181217_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilot',
            old_name='race_count',
            new_name='races_count',
        ),
    ]
