# Generated by Django 2.1.4 on 2018-12-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='toy',
            name='toy_category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
